"""Initial migration

Revision ID: c1a68599dd4d
Revises:
Create Date: 2026-01-02 18:04:14.242056

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "c1a68599dd4d"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
